name: .NET Core CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: List directory structure
      run: ls -R

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.415

    - name: Build main project
      run: dotnet build NameSorter/NameSorter.csproj --configuration Release

    - name: Build test project
      run: dotnet build NameSorterTests/NameSorterTests.csproj --configuration Release

    - name: Test
      run: dotnet test NameSorterTests/NameSorterTests.csproj
