name: .NET Core CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Using v2 as it's the latest stable version as of now.

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2  # Updated to v2
      with:
        dotnet-version: 3.1.415

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test
